# Sources are all project source files, excluding system files
SOURCES = main.c

# Module is the name of the main module buit by this makefile
APPMOD = AccelTestZolertiaZ1

# --------------------------------------------------------------------
# Set the key variables
PROJDIR = $(CURDIR)
ifndef OSW
  OSW = $(PROJDIR)/../../..
endif

# Include the main makefile
include ${OSW}/src/make/Makefile
